### ISSUE TITLE
example seems to be copied from onedrive-sdk-python project without library changes

### ISSUE THREAD

**Issue by eduvik** [microsoftarchive/msgraph-sdk-python#15]
The example code seems to be almost identical to https://github.com/OneDrive/onedrive-sdk-python/blob/master/examples/CommandLineFileExplorer.py but is expecting things to exist in the library that are no longer there (e.g. helpers, get_default_client). 

You should either re-write the example so it works with this SDK, or delete it to prevent confusion

**Comment by jamescro** [comment]
Thanks very much for your feedback. Please feel free to comment in every aspect of this sample so that we can make it as idiomatically Pythonic as possible. I will scrub it as thoroughly as I can from your feedback. I was not aware of the OneDrive sample that you mention, but it's not surprising that you see a close resemblance, since the OneDrive and Microsoft Graph sdks were built with similar technologies and principles. We need to have a Python sample for the Microsoft Graph SDK, so we'll improve this one as best we can. Please let us know what we can do better as we update this sample. Thanks!

**Comment by MIchaelMainer** [comment]
Again, thank you for reporting this issue along with the other ones.

**Comment by caitlinrussell** [comment]
I have deprecated the existing sample and will be tracking the work to create a new one here: #20
